from collections.abc import Sequence
from typing import TypeAlias, Any

from numpy.typing import NDArray

FloatingPointDataSlice: TypeAlias = Sequence[float] | list[float] | NDArray
UniformTypeDataSlice: TypeAlias = Sequence[int | float | str] | NDArray

class InvalidBaseline(Exception): ...

def check_and_convert_type[T](arr: list[T] | NDArray | Sequence[T]) -> NDArray: ...
def cast_floating_point_slice(arr: FloatingPointDataSlice) -> NDArray: ...
def _is_numpy[T](arr: list[T] | NDArray | Sequence[T]) -> bool: ...
def _is_uniform_type[T](arr: list[T]) -> bool: ...

def _extract_sequence_type(arr: Sequence[Any]) -> type: ...
def _convert_obj_type(arr: list[str | float | int]) -> NDArray: ...
