from typing import Union, List
from numpy.typing import NDArray
from .models import MachineLearningMetric

class InvalidBaseline(Exception): ...

def check_and_convert_type(
    arr: Union[List[Union[str, float, int]], NDArray]
) -> NDArray: ...
def _is_numpy(arr: Union[List[Union[str, float, int]], NDArray]) -> bool: ...
def _is_uniform_type(arr: List[Union[str, float, int]]) -> bool: ...
def _convert_obj_type(arr: List[Union[str, float, int]]) -> NDArray: ...
def _map_metric_enum(metric: Union[str, MachineLearningMetric]) -> str: ...
