from collections.abc import Iterable
from typing import TypeAlias
from numpy.typing import NDArray

FloatingPointDataSlice: TypeAlias = Iterable[float] | list[float] | NDArray

class InvalidBaseline(Exception): ...

def check_and_convert_type(
    arr: list[str | float | int] | NDArray | Iterable[float],
) -> NDArray: ...
def cast_floating_point_slice(arr: FloatingPointDataSlice) -> NDArray: ...
def _is_numpy(arr: list[str | float | int] | NDArray | Iterable[float]) -> bool: ...
def _is_uniform_type(arr: list[str | float | int]) -> bool: ...
def _convert_obj_type(arr: list[str | float | int]) -> NDArray: ...
