from abc import ABC
from typing import Protocol, Self
from collections.abc import Iterable
from ..models import (
    DriftReport,
    PerformanceSnapshot,
    DriftSnapshot,
    ModelPerformanceDriftMetric,
    ClassificationDriftMetric,
    LinearRegressionDriftMetric,
)

class LabelBound(Protocol):
    def __eq__(self, other: Self, /) -> bool: ...

class ModelPerfStreamingBase[T](ABC):
    def reset_baseline(self, y_true: Iterable[T], y_pred: Iterable[T]) -> None: ...
    def update_stream(self, y_true: T, y_pred: T) -> None: ...
    def update_stream_batch(self, y_true: Iterable[T], y_pred: Iterable[T]) -> None: ...
    def flush(self) -> None: ...
    def performance_snapshot(self) -> PerformanceSnapshot: ...
    def drift_snapshot(self) -> DriftSnapshot: ...
    def drift_report(self, drift_threshold: float) -> DriftReport: ...
    def drift_report_partial_metrics(
        self, metrics: list[ModelPerformanceDriftMetric], drift_threshold: float
    ) -> DriftReport: ...

class LabeledStreamingBase[T: LabelBound](ModelPerfStreamingBase[T]): ...

class BinaryClassificationStreaming[T: LabelBound](LabeledStreamingBase[T]):
    def __init__(
        self,
        label: T,
        y_true: Iterable[T],
        y_pred: Iterable[T],
    ) -> None: ...
    def update_stream(self, y_true: T, y_pred: T) -> None: ...
    def update_stream_batch(self, y_true: Iterable[T], y_pred: Iterable[T]) -> None: ...
    def flush(self) -> None: ...
    def reset_baseline(self, y_true: Iterable[T], y_pred: Iterable[T]) -> None: ...
    def reset_baseline_and_label(
        self,
        label: T,
        y_true: Iterable[T],
        y_pred: Iterable[T],
    ) -> None: ...
    def performance_snapshot(self) -> PerformanceSnapshot: ...
    def drift_snapshot(self) -> DriftSnapshot: ...
    def drift_report(self, drift_threshold: float) -> DriftReport: ...
    def drift_report_partial_metrics(
        self, metrics: list[ClassificationDriftMetric], drift_threshold: float
    ) -> DriftReport: ...

class LinearRegressionStreaming(ModelPerfStreamingBase[float]):
    def __init__(self, y_true: Iterable[float], y_pred: Iterable[float]) -> None: ...
    def update_stream(self, y_true: float, y_pred: float) -> None: ...
    def update_stream_batch(self, y_true: Iterable[float], y_pred: Iterable[float]) -> None: ...
    def reset_baseline(self, y_true: Iterable[float], y_pred: Iterable[float]) -> None: ...
    def flush(self) -> None: ...
    def performance_snapshot(self) -> PerformanceSnapshot: ...
    def drift_snapshot(self) -> DriftSnapshot: ...
    def drift_report(self, drift_threshold: float) -> DriftReport: ...
    def drift_report_partial_metrics(
        self, metrics: list[LinearRegressionDriftMetric], drift_threshold: float
    ) -> DriftReport: ...

class LogisticRegressionStreaming(ModelPerfStreamingBase[float]):
    def __init__(
        self,
        y_true: Iterable[float],
        y_pred: Iterable[float],
        threshold: float | None = ...,
    ) -> None: ...
    def update_stream(self, y_true: float, y_pred: float) -> None: ...
    def update_stream_batch(self, y_true: Iterable[float], y_pred: Iterable[float]) -> None: ...
    def flush(self) -> None: ...
    def reset_baseline(self, y_true: Iterable[float], y_pred: Iterable[float]) -> None: ...
    def reset_baseline_and_decision_threshold(
        self, y_true: Iterable[float], y_pred: Iterable[float], threshold: float
    ) -> None: ...
    def performance_snapshot(self) -> PerformanceSnapshot: ...
    def drift_snapshot(self) -> DriftSnapshot: ...
    def drift_report(self, drift_threshold: float) -> DriftReport: ...
    def drift_report_partial_metrics(
        self, metrics: list[ClassificationDriftMetric], drift_threshold: float
    ) -> DriftReport: ...
