from abc import ABC
from collections.abc import Iterable

from .base import (DataDriftMetric, FloatingPointDataSlice, QuantileConfig,
                   StringBound)

class DataDriftStreamingBase[T, R](ABC):
    def reset_baseline(self, new_baseline: list[T]) -> None: ...
    def update_stream(self, example: T) -> None: ...
    def update_stream_batch(self, runtime_data: list[T]) -> None: ...
    def compute_drift(self, drift_metric: DataDriftMetric) -> float: ...
    def compute_drift_multiple_criteria(
        self, drift_metrics: list[DataDriftMetric]
    ) -> list[float]: ...
    @property
    def total_samples(self) -> int: ...
    @property
    def num_bins(self) -> int: ...
    def export_snapshot(self) -> R: ...
    def export_baseline(self) -> dict: ...

class StreamingContinuousDataDriftFlush(DataDriftStreamingBase[float, dict[str, list[float]]]):
    def __init__(
        self,
        baseline_dataset: FloatingPointDataSlice,
        quantile_type: QuantileConfig,
        flush_rate: int | None,
        flush_cadence: int | None,
    ) -> None: ...
    def reset_baseline(self, new_baseline: FloatingPointDataSlice) -> None: ...
    def update_stream(self, example: float) -> None: ...
    def update_stream_batch(self, runtime_data: FloatingPointDataSlice) -> None: ...
    def compute_drift(self, drift_metric: DataDriftMetric) -> float: ...
    def compute_drift_multiple_criteria(
        self, drift_metrics: list[DataDriftMetric]
    ) -> list[float]: ...
    @property
    def total_samples(self) -> int: ...
    @property
    def num_bins(self) -> int: ...
    def export_snapshot(self) -> dict[str, list[float]]: ...
    def export_baseline(self) -> dict: ...
    def flush(self) -> None: ...
    def last_flush(self) -> int: ...

class StreamingContinuousDataDriftDecay(DataDriftStreamingBase[float, dict[str, list[float]]]):
    def __init__(
        self,
        baseline_dataset: FloatingPointDataSlice,
        quantile_type: QuantileConfig,
        decay_half_life: int | None,
    ) -> None: ...
    def reset_baseline(self, new_baseline: FloatingPointDataSlice) -> None: ...
    def update_stream(self, example: float) -> None: ...
    def update_stream_batch(self, runtime_data: FloatingPointDataSlice) -> None: ...
    def compute_drift(self, drift_metric: DataDriftMetric) -> float: ...
    def compute_drift_multiple_criteria(
        self, drift_metrics: list[DataDriftMetric]
    ) -> list[float]: ...
    @property
    def total_samples(self) -> int: ...
    @property
    def num_bins(self) -> int: ...
    def export_snapshot(self) -> dict[str, list[float]]: ...
    def export_baseline(self) -> dict: ...

class StreamingCategoricalDataDriftFlush(DataDriftStreamingBase[StringBound, dict[str, float]]):
    def __init__(
        self,
        baseline_dataset: Iterable[StringBound],
        flush_rate: int | None,
        flush_cadence: int | None,
    ) -> None: ...
    def reset_baseline(self, new_baseline: Iterable[StringBound]) -> None: ...
    def update_stream(self, example: StringBound) -> None: ...
    def update_stream_batch(self, runtime_data: Iterable[StringBound]) -> None: ...
    def compute_drift(self, drift_metric: DataDriftMetric) -> float: ...
    def compute_drift_multiple_criteria(
        self, drift_metrics: list[DataDriftMetric]
    ) -> list[float]: ...
    @property
    def total_samples(self) -> int: ...
    @property
    def n_bins(self) -> int: ...
    def export_snapshot(self) -> dict[str, float]: ...
    def export_baseline(self) -> dict: ...
    def flush(self) -> None: ...
    def last_flush(self) -> int: ...

class StreamingCategoricalDataDriftDecay(DataDriftStreamingBase[StringBound, dict[str, float]]):
    def __init__(
        self,
        baseline_dataset: Iterable[StringBound],
        decay_half_life: int,
    ) -> None: ...
    def reset_baseline(self, new_baseline: Iterable[StringBound]) -> None: ...
    def update_stream(self, example: StringBound) -> None: ...
    def update_stream_batch(self, runtime_data: Iterable[StringBound]) -> None: ...
    def compute_drift(self, drift_metric: DataDriftMetric) -> float: ...
    def compute_drift_multiple_criteria(
        self, drift_metrics: list[DataDriftMetric]
    ) -> list[float]: ...
    @property
    def total_samples(self) -> int: ...
    @property
    def n_bins(self) -> int: ...
    def export_snapshot(self) -> dict[str, float]: ...
    def export_baseline(self) -> dict: ...
